student_names=["GUFFRAN","YASHWANTH","SINGH","SURAJ","PRAJWAL","PUNITH","RAHUL","LORD","KING","HUGE","11","@1"]
print(student_names)
student_names[1]="ANUSHREE"
print(student_names)
print(len(student_names))
student_names.append("JANANI")
print(student_names)
student_names.remove("JANANI")
print(student_names)
student_names.remove("KING")
print(student_names)
student_names.insert(1,"SPOO")
student_names.insert(1,"JACKI")
student_names.insert(1,"SHAAN")
student_names.insert(1,"SMRITI")
student_names.insert(1,"LOKY")
print(student_names)
student_names.pop(2)
student_names.pop(4)
print(student_names)
print(len(student_names))
student_names.sort()
print(student_names)
print(type(student_names))


